import type { AchievementCategory } from '../models/types';

export interface AchievementDefinition {
  id: string;
  name: string;
  category: AchievementCategory;
  description: string;
  requirement: string;
}

export const ACHIEVEMENT_DEFS: AchievementDefinition[] = [
  {
    id: 'CF_100',
    name: 'First Compute Budget',
    category: 'milestone',
    description: 'The finance team has noticed the compute ledger exists.',
    requirement: 'Earn 100 total Compute.',
  },
  {
    id: 'CF_1K',
    name: 'Small Batch Processing',
    category: 'milestone',
    description: 'A measurable workload is finally running.',
    requirement: 'Earn 1,000 total Compute.',
  },
  {
    id: 'CF_100K',
    name: 'Real Service Load',
    category: 'milestone',
    description: 'The datacenter is no longer a lab experiment.',
    requirement: 'Earn 100,000 total Compute.',
  },
  {
    id: 'CF_10M',
    name: 'Regional Demand',
    category: 'milestone',
    description: 'Internal customers are lining up for capacity.',
    requirement: 'Earn 10,000,000 total Compute.',
  },
  {
    id: 'CF_1B',
    name: 'Cloud Balance Sheet',
    category: 'milestone',
    description: 'Compute is now a serious line item.',
    requirement: 'Earn 1,000,000,000 total Compute.',
  },
  {
    id: 'CF_10B',
    name: 'Transformation Case',
    category: 'milestone',
    description: 'Enough scale exists to justify a cloud transformation.',
    requirement: 'Earn 10,000,000,000 total Compute.',
  },
  {
    id: 'HW_T0',
    name: 'Desktop Repurposed',
    category: 'hardware',
    description: 'Somebody volunteered an old tower PC.',
    requirement: 'Own at least one Tower PC.',
  },
  {
    id: 'HW_T1',
    name: 'Rack Mounted',
    category: 'hardware',
    description: 'The first proper rack server is online.',
    requirement: 'Own at least one Rack Server.',
  },
  {
    id: 'HW_T2',
    name: 'Blade Density',
    category: 'hardware',
    description: 'Compute density is becoming the plan.',
    requirement: 'Own at least one Blade Server.',
  },
  {
    id: 'HW_T3',
    name: 'Farm Operator',
    category: 'hardware',
    description: 'Single machines are no longer the unit of planning.',
    requirement: 'Own at least one Server Farm.',
  },
  {
    id: 'HW_T4',
    name: 'Mini DC Approved',
    category: 'hardware',
    description: 'A signed purchase request became real capacity.',
    requirement: 'Own at least one Mini Datacenter.',
  },
  {
    id: 'HW_T5',
    name: 'Regional Footprint',
    category: 'hardware',
    description: 'The platform now has regional-scale hardware.',
    requirement: 'Own at least one Regional DC.',
  },
  {
    id: 'HW_T6',
    name: 'Hyperscale Operator',
    category: 'hardware',
    description: 'Mega Datacenter capacity is now part of the fleet.',
    requirement: 'Own at least one Mega Datacenter.',
  },
  {
    id: 'HW_T7',
    name: 'Quantum Capacity',
    category: 'hardware',
    description: 'The platform has crossed into experimental compute.',
    requirement: 'Own at least one Quantum Node.',
  },
  {
    id: 'FAC_100U_USED',
    name: 'North Zone Saturation',
    category: 'expansion',
    description: 'The original room is carrying a real load.',
    requirement: 'Use at least 100U of rack space.',
  },
  {
    id: 'FAC_CENTRAL',
    name: 'Central Zone Online',
    category: 'expansion',
    description: 'Capacity planning has escaped the first room.',
    requirement: 'Unlock Central Zone.',
  },
  {
    id: 'FAC_SOUTH',
    name: 'South Zone Online',
    category: 'expansion',
    description: 'A multi-zone operation is now active.',
    requirement: 'Unlock South Zone.',
  },
  {
    id: 'FAC_1000U',
    name: 'Thousand U Plan',
    category: 'expansion',
    description: 'Facilities has started measuring in rows, not racks.',
    requirement: 'Reach 1,000U total rack capacity.',
  },
  {
    id: 'OPS_PUE_18',
    name: 'Cooling Retrofit',
    category: 'efficiency',
    description: 'The first efficiency project survived procurement.',
    requirement: 'Upgrade cooling to PUE 1.80.',
  },
  {
    id: 'OPS_PUE_16',
    name: 'Efficient Plant',
    category: 'efficiency',
    description: 'Power waste is finally under control.',
    requirement: 'Upgrade cooling to PUE 1.60.',
  },
  {
    id: 'OPS_SAT_90',
    name: 'Happy Stakeholders',
    category: 'efficiency',
    description: 'Service quality is high enough that people stop escalating.',
    requirement: 'Reach 90% satisfaction.',
  },
  {
    id: 'OPS_CPS_1K',
    name: 'Four Digit Throughput',
    category: 'efficiency',
    description: 'The operation now produces serious net compute.',
    requirement: 'Reach 1,000 net CPS.',
  },
  {
    id: 'OPS_CPS_100K',
    name: 'Industrial Throughput',
    category: 'efficiency',
    description: 'Compute output has become an industrial process.',
    requirement: 'Reach 100,000 net CPS.',
  },
  {
    id: 'PR_FIRST',
    name: 'Signed Purchase Request',
    category: 'bureaucracy',
    description: 'The first large hardware order entered the workflow.',
    requirement: 'Create at least one procurement request.',
  },
  {
    id: 'PR_BLOCKED',
    name: 'Dock Needs Rack Space',
    category: 'bureaucracy',
    description: 'A delivery arrived before facilities were ready.',
    requirement: 'Have a blocked procurement request.',
  },
  {
    id: 'AUDIT_1',
    name: 'Evidence Submitted',
    category: 'audit',
    description: 'A real audit was answered before the deadline.',
    requirement: 'Resolve one audit event.',
  },
  {
    id: 'AUDIT_5',
    name: 'Audit Muscle Memory',
    category: 'audit',
    description: 'Compliance work has become repeatable.',
    requirement: 'Resolve five audit events.',
  },
  {
    id: 'PRESTIGE_1',
    name: 'Cloud Transformation',
    category: 'prestige',
    description: 'The first transformation reset created lasting reputation.',
    requirement: 'Prestige once.',
  },
  {
    id: 'PRESTIGE_2',
    name: 'IPO',
    category: 'prestige',
    description: 'Reputation was converted into permanent influence.',
    requirement: 'Execute Prestige Tier 2 once.',
  },
  {
    id: 'REP_5',
    name: 'Reputation Budget',
    category: 'prestige',
    description: 'The organization now trusts long-term platform bets.',
    requirement: 'Hold at least 5 Reputation.',
  },
  {
    id: 'INF_5',
    name: 'Board-Level Access',
    category: 'prestige',
    description: 'Influence now changes platform economics permanently.',
    requirement: 'Hold at least 5 Influence.',
  },
  {
    id: 'INF_10',
    name: 'Market Maker',
    category: 'prestige',
    description: 'The company can shape its own operating environment.',
    requirement: 'Hold at least 10 Influence.',
  },
  {
    id: 'TECH_1',
    name: 'First Architecture Decision',
    category: 'technology',
    description: 'The tech roadmap has moved from slideware to reality.',
    requirement: 'Unlock one technology.',
  },
  {
    id: 'TECH_5',
    name: 'Platform Practice',
    category: 'technology',
    description: 'Several capabilities now reinforce each other.',
    requirement: 'Unlock five technologies.',
  },
  {
    id: 'TECH_10',
    name: 'Strategic Roadmap',
    category: 'technology',
    description: 'The technology program has real depth.',
    requirement: 'Unlock ten technologies.',
  },
  {
    id: 'TECH_20',
    name: 'Reference Architecture',
    category: 'technology',
    description: 'Every v0.8 technology path is complete.',
    requirement: 'Unlock all twenty technologies.',
  },
];
