import {
  CreditRating, FacilityRegion, CoolingLevel, ClimateRisk,
  StaffRole, IncidentType, IncidentSeverity, AcquisitionStatus,
  ComplianceCertType,
} from '../core/types';
import type { GameConfig } from '../core/types';

export const DEFAULT_CONFIG: Readonly<GameConfig> = Object.freeze({
  meta: {
    startYear: 2000,
    startMonth: 1,
    startCash: 5_000_000,  // NT$5,000,000 (天使輪資金)
    gameMode: 'standard' as const,
  },
  time: {
    msPerGameMonthAt1x: 60_000,  // 60 秒現實 = 1 遊戲月 (1x)
    startDate: { year: 2000, month: 1 },
    autoPauseOnP1: true,
    autoPauseOnP2: true,
    autoPauseOnRFP: true,
    autoPauseOnMajorEvent: true,
    autoPauseOnMonthEnd: true,
    autoPauseOnCashWarning: true,
    autoPauseOnEOLWarning: false,
    autoPauseOnContractExpiry: true,
  },
  finance: {
    corporateTaxRate: 0.17,
    staffBenefitMultiplier: 1.3,
    creditRatingUpdateIntervalMonths: 3,
    bankruptcyConsecutiveLossMonths: 3,
    cashWarningMultiplier: 2,
    slaBreachPayoutCap: 3.0,
    depreciation: {
      server: 60,
      networking: 84,
      storage: 60,
      ups: 120,
      facility: 240,
      residualRate: 0.10,
    },
    loanTerms: {
      [CreditRating.AAA]:      { maxMultiple: 36, annualRate: 0.025, maxMonths: 84 },
      [CreditRating.AA]:       { maxMultiple: 24, annualRate: 0.035, maxMonths: 60 },
      [CreditRating.A]:        { maxMultiple: 18, annualRate: 0.045, maxMonths: 36 },
      [CreditRating.BBB]:      { maxMultiple: 12, annualRate: 0.065, maxMonths: 24 },
      [CreditRating.BB]:       { maxMultiple:  6, annualRate: 0.090, maxMonths: 12 },
      [CreditRating.B]:        { maxMultiple:  3, annualRate: 0.150, maxMonths:  6 },
      [CreditRating.Insolvent]:{ maxMultiple:  0, annualRate: 0.000, maxMonths:  0 },
    },
    centralBankRateHistory: [
      { fromYear: 2000, rate: 0.0525 },
      { fromYear: 2002, rate: 0.0175 },
      { fromYear: 2005, rate: 0.0325 },
      { fromYear: 2008, rate: 0.0125 },
      { fromYear: 2010, rate: 0.0150 },
      { fromYear: 2015, rate: 0.0125 },
      { fromYear: 2022, rate: 0.0475 },
      { fromYear: 2024, rate: 0.0350 },
    ],
  },
  facility: {
    regions: {
      [FacilityRegion.North]: {
        initialUnits: 100,
        baseMonthlyRent: 200_000,
        performanceBonus: 1.0,
        climateRisk: ClimateRisk.Low,
      },
      [FacilityRegion.Central]: {
        initialUnits: 500,
        baseMonthlyRent: 800_000,
        performanceBonus: 1.15,
        climateRisk: ClimateRisk.Medium,
        unlockMinMonthlyRevenue: 1_000_000,
      },
      [FacilityRegion.South]: {
        initialUnits: 2000,
        baseMonthlyRent: 2_500_000,
        performanceBonus: 1.30,
        climateRisk: ClimateRisk.High,
        unlockMinMonthlyRevenue: 10_000_000,
      },
    },
    coolingLevels: {
      [CoolingLevel.Open]:      { pue: 2.00, investmentCost: 0,         unlockYear: 2000 },
      [CoolingLevel.BasicAC]:   { pue: 1.80, investmentCost: 500_000,   unlockYear: 2000 },
      [CoolingLevel.HotAisle]:  { pue: 1.60, investmentCost: 1_500_000, unlockYear: 2002 },
      [CoolingLevel.Chiller]:   { pue: 1.40, investmentCost: 5_000_000, unlockYear: 2005 },
      [CoolingLevel.InRow]:     { pue: 1.25, investmentCost: 8_000_000, unlockYear: 2008 },
      [CoolingLevel.Liquid]:    { pue: 1.10, investmentCost: 15_000_000, unlockYear: 2013 },
      [CoolingLevel.Immersion]: { pue: 1.05, investmentCost: 30_000_000, unlockYear: 2018 },
    },
    expansionCostMultiplier: 24,
    expansionCapacityMultiplier: 0.5,
    capacityWarningThreshold: 0.85,
    geoRedundancyThreshold: 0.50,
    geoRedundancySLABonus: -0.30,
    electricityRates: [
      { fromYear: 2000, ratePerKwh: 2.50 },
      { fromYear: 2008, ratePerKwh: 2.80 },
      { fromYear: 2013, ratePerKwh: 3.10 },
      { fromYear: 2018, ratePerKwh: 3.30 },
      { fromYear: 2022, ratePerKwh: 3.80 },
    ],
    hoursPerMonth: 744,
  },
  hardware: {
    eolWarningMonthsBefore: 3,
    installationMonthsPerUnit: 0,
    largePurchaseThreshold: 5_000_000,
    requisitionDeliveryDelay: 1,
    requisitionDiscount: 0.75,
    installmentMonths: 24,
    eolFailureMultipliers: [1.0, 1.5, 2.0, 3.0] as [number, number, number, number],
    salvageValueRate: 0.10,
  },
  software: {
    eosWarningMonthsBefore: 3,
    eosSecurityMultipliers: { quarter1: 1.2, quarter2: 1.5, quarter3plus: 2.0 },
    eosComplianceScorePenalty: { quarter1: -30, quarter2: -50, quarter3plus: -70 },
    compliancePenaltyAmount: 500_000,
  },
  contract: {
    rfpResponseWindowMonths: 1,
    renewalNoticeMonths: 1,
    baseRFPsPerMonth: 1.5,
    maxMonthlyPenaltyCap: 3.0,
    churnProbabilities: {
      dataBreachAndLate: 0.70,
      consecutiveSLABreach: 0.50,
      p1Over24Hours: 0.40,
      lowSatisfactionProlonged: 0.30,
      competitorOffer: 0.20,
    },
  },

  staff: {
    roles: {
      [StaffRole.E1_NOC]:       { baseSalaryNTD: 38_000, managementCapacityU: 10, handlingPower: 0.5, recruitmentMonths: 0.5, promotionRequirements: { minMonths: 12, cost: 50_000  }, unlockYear: 2000 },
      [StaffRole.E2_SysEng]:    { baseSalaryNTD: 55_000, managementCapacityU: 20, handlingPower: 1.0, recruitmentMonths: 1,   promotionRequirements: { minMonths: 18, cost: 80_000  }, unlockYear: 2000 },
      [StaffRole.E3_SecAna]:    { baseSalaryNTD: 72_000, managementCapacityU: 30, handlingPower: 2.0, recruitmentMonths: 1.5, promotionRequirements: { minMonths: 24, cost: 120_000 }, unlockYear: 2001 },
      [StaffRole.E3_Senior]:    { baseSalaryNTD: 75_000, managementCapacityU: 35, handlingPower: 2.0, recruitmentMonths: 1.5, promotionRequirements: { minMonths: 24, cost: 120_000 }, unlockYear: 2001 },
      [StaffRole.E4_CloudArch]: { baseSalaryNTD: 110_000, managementCapacityU: 50, handlingPower: 4.0, recruitmentMonths: 2, promotionRequirements: { minMonths: 36, cost: 200_000 }, unlockYear: 2005 },
      [StaffRole.E4_AIEng]:     { baseSalaryNTD: 120_000, managementCapacityU: 40, handlingPower: 4.0, recruitmentMonths: 2, promotionRequirements: { minMonths: 36, cost: 200_000 }, unlockYear: 2018 },
      [StaffRole.E5_CISO]:      { baseSalaryNTD: 180_000, managementCapacityU: 80, handlingPower: 8.0, recruitmentMonths: 3, promotionRequirements: { minMonths: 48, cost: 400_000 }, unlockYear: 2004 },
    },
    benefitMultiplier: 1.3,
    baseAnnualResignationRate: 0.10,
    salaryInflationRate: 0.025,
    coverageRatioThresholds: { optimal: 1.0, warning: 0.7, critical: 0.5, severe: 0.3 },
    interviewQuestionCount: 3,
    severanceMonthsPerYear: 1,
  },

  security: {
    baseIncidentRates: {
      [IncidentType.HardwareFailure]:   0.05,
      [IncidentType.NetworkOutage]:     0.04,
      [IncidentType.CapacityAlarm]:     0.08,
      [IncidentType.PowerAnomaly]:      0.03,
      [IncidentType.CoolingFailure]:    0.02,
      [IncidentType.Ransomware]:        0.015,
      [IncidentType.DataBreach]:        0.01,
      [IncidentType.SocialEngineering]: 0.02,
      [IncidentType.APTAttack]:         0.005,
      [IncidentType.DDoS]:              0.025,
      [IncidentType.ComplianceGap]:     0.03,
      [IncidentType.InsiderThreat]:     0.008,
      [IncidentType.SupplyChainAttack]: 0.005,
    },
    incidentSeverity: {
      [IncidentType.HardwareFailure]:   IncidentSeverity.P3,
      [IncidentType.NetworkOutage]:     IncidentSeverity.P2,
      [IncidentType.CapacityAlarm]:     IncidentSeverity.P3,
      [IncidentType.PowerAnomaly]:      IncidentSeverity.P2,
      [IncidentType.CoolingFailure]:    IncidentSeverity.P2,
      [IncidentType.Ransomware]:        IncidentSeverity.P1,
      [IncidentType.DataBreach]:        IncidentSeverity.P1,
      [IncidentType.SocialEngineering]: IncidentSeverity.P3,
      [IncidentType.APTAttack]:         IncidentSeverity.P1,
      [IncidentType.DDoS]:              IncidentSeverity.P2,
      [IncidentType.ComplianceGap]:     IncidentSeverity.P4,
      [IncidentType.InsiderThreat]:     IncidentSeverity.P2,
      [IncidentType.SupplyChainAttack]: IncidentSeverity.P2,
    },
    baseResolutionHours: {
      [IncidentType.HardwareFailure]:   8,
      [IncidentType.NetworkOutage]:     4,
      [IncidentType.CapacityAlarm]:     2,
      [IncidentType.PowerAnomaly]:      6,
      [IncidentType.CoolingFailure]:    6,
      [IncidentType.Ransomware]:        72,
      [IncidentType.DataBreach]:        48,
      [IncidentType.SocialEngineering]: 12,
      [IncidentType.APTAttack]:         96,
      [IncidentType.DDoS]:              8,
      [IncidentType.ComplianceGap]:     24,
      [IncidentType.InsiderThreat]:     36,
      [IncidentType.SupplyChainAttack]: 48,
    },
    deadlineHours: {
      [IncidentSeverity.P1]: 4,
      [IncidentSeverity.P2]: 8,
      [IncidentSeverity.P3]: 24,
      [IncidentSeverity.P4]: 48,
    },
    hourlyLossRate: {
      [IncidentSeverity.P1]: 0.05,
      [IncidentSeverity.P2]: 0.02,
      [IncidentSeverity.P3]: 0.005,
      [IncidentSeverity.P4]: 0.001,
    },
    complianceScoreThresholds: { bonus: 80, neutral: 60, penalty1: 40, penalty2: 0 },
    ransomPaymentRate: 0.20,
    dataBreachReportWindowHours: 72,
  },

  eventTimeline: {
    economicCycleDurationRange: [8, 15] as [number, number],
    randomEventCooldownRange: [2, 6] as [number, number],
    baseInflationRate: 0.02,
    inflationVolatility: 0.005,
    baseExchangeRate: 30.0,
    exchangeRateMonthlyVolatility: 0.003,
  },

  techTree: {
    cancelRefundRate: 0.50,
    milestoneRequiredNodes: 20,
  },

  reputation: {
    initialScore: 75,
    naturalRecoveryPerMonth: 1,
    naturalRecoveryThreshold: 80,
    highSatisfactionThreshold: 80,
    lowSatisfactionThreshold: 50,
    criticalSatisfactionThreshold: 40,
    renewalBonusAtHighSatisfaction: 0.40,
    priceIncreaseRange: [0.05, 0.15] as [number, number],
  },

  strategy: {
    establishThreshold: 0.60,
    reputationBonusOnEstablish: 5,
    rfpBoostOnRoute: 0.30,
  },

  customer: {
    referralCheckMonths: 3,
    xlChurnReputationPenalty: 8,
    sChurnReputationPenalty: 2,
    surveyMonth: 12,
    loyaltyRenewalBonus: 0.15,
  },

  vendor: {
    purchasePerPoint: 1_000_000,
    silverThreshold: 30,
    goldThreshold: 60,
    platinumThreshold: 85,
    goldDiscount: 0.10,
    platinumDiscount: 0.15,
    concentrationRiskThreshold: 0.60,
    deliverySpeedupMonths: 1,
  },

  board: {
    bonusMonthsOfRevenue: 1,
    partialBonusMonthsOfRevenue: 0.25,
    warningThreshold: 0.50,
    gameOverConsecutiveFailYears: 2,
    kpiRevenueGrowthTarget: 0.15,
    kpiCustomerCountTarget: 5,
    kpiSlaRateTarget: 95,
    kpiGrossMarginTarget: 20,
  },

  techDebt: {
    eolSoftwarePointsPerMonth: 5,
    skippedMaintenancePoints: 3,
    shortStaffedContractPoints: 2,
    eolHardwareOver2YrsPointsPerMonth: 4,
    emergencyWorkaroundPoints: 1,
    criticalCascadeFailureChance: 0.20,
    criticalThreshold: 81,
    dangerThreshold: 61,
    warningThreshold: 31,
    maxPoints: 100,
    refactorCostPerPoint: 50_000,
  },

  complianceCerts: {
    certDefs: {
      [ComplianceCertType.ISO_27001]: { acquisitionCostNTD: 2_000_000, acquisitionMonths: 12, annualRenewalCostNTD: 500_000, validityYears: 3, prerequisiteSecAnalysts: 2, renewalMonths: 3 },
      [ComplianceCertType.SOC2]:      { acquisitionCostNTD: 1_500_000, acquisitionMonths: 9,  annualRenewalCostNTD: 400_000, validityYears: 2, prerequisiteSecAnalysts: 1, renewalMonths: 2 },
      [ComplianceCertType.HIPAA]:     { acquisitionCostNTD: 800_000,   acquisitionMonths: 6,  annualRenewalCostNTD: 200_000, validityYears: 3, prerequisiteSecAnalysts: 1, renewalMonths: 2 },
      [ComplianceCertType.PCI_DSS]:   { acquisitionCostNTD: 1_200_000, acquisitionMonths: 8,  annualRenewalCostNTD: 300_000, validityYears: 2, prerequisiteSecAnalysts: 1, renewalMonths: 2 },
      [ComplianceCertType.ISO_20000]: { acquisitionCostNTD: 1_000_000, acquisitionMonths: 10, annualRenewalCostNTD: 250_000, validityYears: 3, prerequisiteSecAnalysts: 1, renewalMonths: 2 },
      [ComplianceCertType.CSA_STAR]:  { acquisitionCostNTD: 600_000,   acquisitionMonths: 5,  annualRenewalCostNTD: 150_000, validityYears: 2, prerequisiteSecAnalysts: 1, renewalMonths: 1 },
    },
  },

  expansion: {
    acquisitionUnlockYear: 2008,
    newFacilityUnlockYear: 2010,
    integrationMonths: 6,
    integrationMoralePenalty: -15,
    integrationTechDebt: 30,
    drAbilityBonusFromSecondCity: 50,
    acquisitionTargets: [
      { id: 'acq_01', name: '台中資科', city: '台中', annualRevenue: 12_000_000, customerCount: 4, techDebtInherit: 25, acquisitionMultiplier: 2.5, status: AcquisitionStatus.Available, availableFromYear: 2008 },
      { id: 'acq_02', name: '南部IDC',  city: '台南', annualRevenue: 20_000_000, customerCount: 5, techDebtInherit: 35, acquisitionMultiplier: 3.0, status: AcquisitionStatus.Available, availableFromYear: 2010 },
      { id: 'acq_03', name: '雲端新創', city: '台北', annualRevenue: 30_000_000, customerCount: 3, techDebtInherit: 40, acquisitionMultiplier: 3.5, status: AcquisitionStatus.Available, availableFromYear: 2015 },
    ],
  },

  energy: {
    solarUnlockYear: 2015,
    solarInstallCost: 5_000_000,
    solarMonthlyReduction: 0.12,
    storageUnlockYear: 2018,
    storageInstallCost: 3_000_000,
    storagePeakSavings: 0.08,
    carbonTaxStartYear: 2020,
    carbonTaxMonthly: 100_000,
    greenEsgDiscount: 0.30,
    spotVolatility: 0.20,
    fixed1YDiscount: 0.05,
    fixed3YDiscount: 0.15,
    fixed3YPrepayMonths: 3,
    esgRfpBonus: 0.20,
    esgThresholdForBonus: 70,
  },
});
