import { CreditRating, FacilityRegion, CoolingLevel, ClimateRisk } from '../core/types';
import type { GameConfig } from '../core/types';

export const DEFAULT_CONFIG: Readonly<GameConfig> = Object.freeze({
  meta: {
    startYear: 2000,
    startMonth: 1,
    startCash: 5_000_000,  // NT$5,000,000 (天使輪資金)
    gameMode: 'standard' as const,
  },
  time: {
    msPerGameMonthAt1x: 60_000,  // 60 秒現實 = 1 遊戲月 (1x)
    startDate: { year: 2000, month: 1 },
    autoPauseOnP1: true,
    autoPauseOnP2: true,
    autoPauseOnRFP: true,
    autoPauseOnMajorEvent: true,
    autoPauseOnMonthEnd: true,
    autoPauseOnCashWarning: true,
    autoPauseOnEOLWarning: false,
    autoPauseOnContractExpiry: true,
  },
  finance: {
    corporateTaxRate: 0.17,
    staffBenefitMultiplier: 1.3,
    creditRatingUpdateIntervalMonths: 3,
    bankruptcyConsecutiveLossMonths: 3,
    cashWarningMultiplier: 2,
    slaBreachPayoutCap: 3.0,
    depreciation: {
      server: 60,
      networking: 84,
      storage: 60,
      ups: 120,
      facility: 240,
      residualRate: 0.10,
    },
    loanTerms: {
      [CreditRating.AAA]:      { maxMultiple: 36, annualRate: 0.025, maxMonths: 84 },
      [CreditRating.AA]:       { maxMultiple: 24, annualRate: 0.035, maxMonths: 60 },
      [CreditRating.A]:        { maxMultiple: 18, annualRate: 0.045, maxMonths: 36 },
      [CreditRating.BBB]:      { maxMultiple: 12, annualRate: 0.065, maxMonths: 24 },
      [CreditRating.BB]:       { maxMultiple:  6, annualRate: 0.090, maxMonths: 12 },
      [CreditRating.B]:        { maxMultiple:  3, annualRate: 0.150, maxMonths:  6 },
      [CreditRating.Insolvent]:{ maxMultiple:  0, annualRate: 0.000, maxMonths:  0 },
    },
    centralBankRateHistory: [
      { fromYear: 2000, rate: 0.0525 },
      { fromYear: 2002, rate: 0.0175 },
      { fromYear: 2005, rate: 0.0325 },
      { fromYear: 2008, rate: 0.0125 },
      { fromYear: 2010, rate: 0.0150 },
      { fromYear: 2015, rate: 0.0125 },
      { fromYear: 2022, rate: 0.0475 },
      { fromYear: 2024, rate: 0.0350 },
    ],
  },
  facility: {
    regions: {
      [FacilityRegion.North]: {
        initialUnits: 100,
        baseMonthlyRent: 200_000,
        performanceBonus: 1.0,
        climateRisk: ClimateRisk.Low,
      },
      [FacilityRegion.Central]: {
        initialUnits: 500,
        baseMonthlyRent: 800_000,
        performanceBonus: 1.15,
        climateRisk: ClimateRisk.Medium,
        unlockMinMonthlyRevenue: 1_000_000,
      },
      [FacilityRegion.South]: {
        initialUnits: 2000,
        baseMonthlyRent: 2_500_000,
        performanceBonus: 1.30,
        climateRisk: ClimateRisk.High,
        unlockMinMonthlyRevenue: 10_000_000,
      },
    },
    coolingLevels: {
      [CoolingLevel.Open]:      { pue: 2.00, investmentCost: 0,         unlockYear: 2000 },
      [CoolingLevel.BasicAC]:   { pue: 1.80, investmentCost: 500_000,   unlockYear: 2000 },
      [CoolingLevel.HotAisle]:  { pue: 1.60, investmentCost: 1_500_000, unlockYear: 2002 },
      [CoolingLevel.Chiller]:   { pue: 1.40, investmentCost: 5_000_000, unlockYear: 2005 },
      [CoolingLevel.InRow]:     { pue: 1.25, investmentCost: 8_000_000, unlockYear: 2008 },
      [CoolingLevel.Liquid]:    { pue: 1.10, investmentCost: 15_000_000, unlockYear: 2013 },
      [CoolingLevel.Immersion]: { pue: 1.05, investmentCost: 30_000_000, unlockYear: 2018 },
    },
    expansionCostMultiplier: 24,
    expansionCapacityMultiplier: 0.5,
    capacityWarningThreshold: 0.85,
    geoRedundancyThreshold: 0.50,
    geoRedundancySLABonus: -0.30,
    electricityRates: [
      { fromYear: 2000, ratePerKwh: 2.50 },
      { fromYear: 2008, ratePerKwh: 2.80 },
      { fromYear: 2013, ratePerKwh: 3.10 },
      { fromYear: 2018, ratePerKwh: 3.30 },
      { fromYear: 2022, ratePerKwh: 3.80 },
    ],
    hoursPerMonth: 744,
  },
  hardware: {
    eolWarningMonthsBefore: 3,
    installationMonthsPerUnit: 0,
    largePurchaseThreshold: 5_000_000,
    requisitionDeliveryDelay: 1,
    requisitionDiscount: 0.75,
    installmentMonths: 24,
    eolFailureMultipliers: [1.0, 1.5, 2.0, 3.0] as [number, number, number, number],
    salvageValueRate: 0.10,
  },
  software: {
    eosWarningMonthsBefore: 3,
    eosSecurityMultipliers: { quarter1: 1.2, quarter2: 1.5, quarter3plus: 2.0 },
    eosComplianceScorePenalty: { quarter1: -30, quarter2: -50, quarter3plus: -70 },
    compliancePenaltyAmount: 500_000,
  },
  contract: {
    rfpResponseWindowMonths: 1,
    renewalNoticeMonths: 1,
    baseRFPsPerMonth: 1.5,
    maxMonthlyPenaltyCap: 3.0,
    churnProbabilities: {
      dataBreachAndLate: 0.70,
      consecutiveSLABreach: 0.50,
      p1Over24Hours: 0.40,
      lowSatisfactionProlonged: 0.30,
      competitorOffer: 0.20,
    },
  },
});
