import type { HardwareDefinition, UpgradeLevel } from '../models/types';

export const HARDWARE_DEFS: HardwareDefinition[] = [
  {
    id: 'T0',
    name: 'Tower PC',
    tier: 0,
    baseCost: 10,
    baseCps: 0.1,
    watts: 35,
    uSize: 2,
    ascii: [
      '  ┌───┐  ',
      '  │CPU│  ',
      '  │   │  ',
      '  └───┘  ',
      '  [___]  ',
    ],
    description: '一台普通的桌上型電腦。不怎麼厲害，但它是你的起點。',
    unlockAt: 0,
  },
  {
    id: 'T1',
    name: 'Rack Server',
    tier: 1,
    baseCost: 100,
    baseCps: 2,
    watts: 150,
    uSize: 2,
    ascii: [
      '  ═══════  ',
      '  ║ SRV ║  ',
      '  ║ ▪▪▪ ║  ',
      '  ═══════  ',
    ],
    description: '標準 2U 機架伺服器。效率遠勝桌機，是真正的起點。',
    unlockAt: 1,
  },
  {
    id: 'T2',
    name: 'Blade Server',
    tier: 2,
    baseCost: 1000,
    baseCps: 20,
    watts: 350,
    uSize: 1,
    ascii: [
      '  [▐█▌▐█▌]  ',
      '  [▐█▌▐█▌]  ',
      '  [▐█▌▐█▌]  ',
    ],
    description: '刀鋒伺服器，高密度部署。每 U 空間效益最大化。',
    unlockAt: 2,
  },
  {
    id: 'T3',
    name: 'Server Farm',
    tier: 3,
    baseCost: 10000,
    baseCps: 200,
    watts: 1200,
    uSize: 5,
    ascii: [
      '  ┌─────────┐  ',
      '  │ ####### │  ',
      '  │ # FARM# │  ',
      '  │ ####### │  ',
      '  └─────────┘  ',
    ],
    description: '伺服器農場。規模效應開始顯現，算力躍升。',
    unlockAt: 5,
  },
  {
    id: 'T4',
    name: 'Mini Datacenter',
    tier: 4,
    baseCost: 100000,
    baseCps: 2000,
    watts: 4000,
    uSize: 20,
    ascii: [
      '  ╔═══════════╗  ',
      '  ║  ▪ DC ▪   ║  ',
      '  ║  MINI     ║  ',
      '  ║  ▪▪▪▪▪▪▪  ║  ',
      '  ╚═══════════╝  ',
    ],
    description: '微型資料中心。需要跑採購簽呈，但值得等待。',
    unlockAt: 10,
  },
  {
    id: 'T5',
    name: 'Regional DC',
    tier: 5,
    baseCost: 1000000,
    baseCps: 20000,
    watts: 15000,
    uSize: 100,
    ascii: [
      '  ╔═══════════════╗  ',
      '  ║  REGIONAL DC  ║  ',
      '  ║  ▪▪▪▪▪▪▪▪▪▪  ║  ',
      '  ║  DATA CENTER  ║  ',
      '  ╚═══════════════╝  ',
    ],
    description: '區域資料中心。需要完整採購流程與主管核准。',
    unlockAt: 15,
  },
  {
    id: 'T6',
    name: 'Mega Datacenter',
    tier: 6,
    baseCost: 10000000,
    baseCps: 200000,
    watts: 80000,
    uSize: 500,
    ascii: [
      '  ╔═══════════════════╗  ',
      '  ║   MEGA DATACENTER  ║  ',
      '  ║  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ║  ',
      '  ║  HYPERSCALE CLOUD  ║  ',
      '  ╚═══════════════════╝  ',
    ],
    description: '超大型資料中心。雲端服務規模。',
    unlockAt: 12,
  },
  {
    id: 'T7',
    name: 'Quantum Node',
    tier: 7,
    baseCost: 1000000000,
    baseCps: 10000000,
    watts: 300000,
    uSize: 200,
    ascii: [
      '  ◈══════════════════◈  ',
      '  ║  ⟨ QUANTUM NODE ⟩ ║  ',
      '  ║  ∞ ENTANGLED ∞    ║  ',
      '  ◈══════════════════◈  ',
    ],
    description: '量子運算節點。突破物理限制的算力奇蹟。',
    unlockAt: 8,
  },
];

export const COST_GROWTH = 1.15;

export const UPGRADE_LEVELS: UpgradeLevel[] = [
  { level: 1, label: 'Lv1', multiplier: 1,   costMultiplier: 0 },
  { level: 2, label: 'Lv2', multiplier: 2,   costMultiplier: 50 },
  { level: 3, label: 'Lv3', multiplier: 5,   costMultiplier: 500 },
  { level: 4, label: 'Lv4', multiplier: 25,  costMultiplier: 5000 },
  { level: 5, label: 'Lv5', multiplier: 100, costMultiplier: 50000 },
];

export const MAX_UPGRADE_LEVEL_V02 = 3; // v0.2 unlocks up to Lv3
