export const PROCUREMENT_REQUIRED_TIER = 4;
export const PROCUREMENT_BASE_LEAD_TIME = 45;
export const PROCUREMENT_TIER_LEAD_TIME_MULTIPLIER = 1.75;
export const PROCUREMENT_SATISFACTION_ON_DELIVERY = 1.5;
export const PROCUREMENT_SATISFACTION_PENDING_PENALTY = 0.015;
export const SATISFACTION_RECOVERY_RATE = 0.02;
export const SATISFACTION_SHUTDOWN_PENALTY = 0.25;
export const SATISFACTION_CAPACITY_PENALTY = 0.04;
