import { SoftwareCategory, LicenseType, SoftwareEffectType } from '../core/types';
import type { SoftwareProduct } from '../core/types';

// ─── Era 1: 2000–2004 ────────────────────────────────────────────────────────

const ERA1_OS: SoftwareProduct[] = [
  {
    id: 'RHEL_3',
    name: 'Red Hat Enterprise Linux 3',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.AnnualSubscription,
    vendor: 'Red Hat',
    unlockYear: 2003,
    eosYear: 2010,
    annualCostNTD: 45_000,
    effects: [{ type: SoftwareEffectType.ComplianceScore, value: 5 }],
    isFreeOpenSource: false,
  },
  {
    id: 'CENTOS_3',
    name: 'CentOS 3',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.OpenSource,
    vendor: 'CentOS',
    unlockYear: 2004,
    eosYear: 2010,
    annualCostNTD: 0,
    effects: [],
    isFreeOpenSource: true,
    notes: 'RHEL clone, zero licensing cost',
  },
  {
    id: 'WIN_SERVER_2003',
    name: 'Windows Server 2003',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Microsoft',
    unlockYear: 2003,
    eosYear: 2015,
    annualCostNTD: 60_000,
    effects: [{ type: SoftwareEffectType.ComplianceScore, value: 3 }],
    isFreeOpenSource: false,
  },
  {
    id: 'WIN_2000_SERVER',
    name: 'Windows 2000 Server',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Microsoft',
    unlockYear: 2000,
    eosYear: 2010,
    annualCostNTD: 48_000,
    effects: [],
    isFreeOpenSource: false,
    upgradePathFrom: [],
  },
];

const ERA1_VIRTUALIZATION: SoftwareProduct[] = [
  {
    id: 'VMWARE_ESX_2',
    name: 'VMware ESX Server 2',
    category: SoftwareCategory.Virtualization,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'VMware',
    unlockYear: 2003,
    eosYear: 2008,
    annualCostNTD: 75_000,
    effects: [{ type: SoftwareEffectType.VirtualizationDensity, value: 2.0 }],
    isFreeOpenSource: false,
    notes: 'Bare-metal hypervisor, 2x VPS density',
  },
  {
    id: 'VMWARE_GSX_3',
    name: 'VMware GSX Server 3',
    category: SoftwareCategory.Virtualization,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'VMware',
    unlockYear: 2003,
    eosYear: 2009,
    annualCostNTD: 44_970,
    effects: [{ type: SoftwareEffectType.VirtualizationDensity, value: 1.5 }],
    isFreeOpenSource: false,
    notes: 'Hosted virtualization, 1.5x density',
  },
  {
    id: 'MS_VIRTUAL_SERVER_2005',
    name: 'Microsoft Virtual Server 2005',
    category: SoftwareCategory.Virtualization,
    licenseType: LicenseType.OpenSource,
    vendor: 'Microsoft',
    unlockYear: 2004,
    eosYear: 2011,
    annualCostNTD: 0,
    effects: [{ type: SoftwareEffectType.VirtualizationDensity, value: 1.3 }],
    isFreeOpenSource: true,
    notes: 'Free, Windows guests only, 1.3x density',
  },
];

const ERA1_BACKUP: SoftwareProduct[] = [
  {
    id: 'NETBACKUP_45',
    name: 'Veritas NetBackup 4.5',
    category: SoftwareCategory.Backup,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Veritas',
    unlockYear: 2001,
    eosYear: 2015,
    annualCostNTD: 150_000,
    effects: [{ type: SoftwareEffectType.BackupCoverage, value: 0.80 }],
    isFreeOpenSource: false,
  },
  {
    id: 'BACKUP_EXEC_8',
    name: 'Veritas Backup Exec 8',
    category: SoftwareCategory.Backup,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Veritas',
    unlockYear: 2001,
    eosYear: 2010,
    annualCostNTD: 30_000,
    effects: [{ type: SoftwareEffectType.BackupCoverage, value: 0.50 }],
    isFreeOpenSource: false,
    notes: 'Windows backup, entry-level',
  },
  {
    id: 'BACULA_OSS',
    name: 'Bacula (Open Source)',
    category: SoftwareCategory.Backup,
    licenseType: LicenseType.OpenSource,
    vendor: 'Bacula Systems',
    unlockYear: 2002,
    eosYear: 9999,
    annualCostNTD: 0,
    effects: [{ type: SoftwareEffectType.BackupCoverage, value: 0.40 }],
    isFreeOpenSource: true,
  },
];

const ERA1_SECURITY: SoftwareProduct[] = [
  {
    id: 'CHECKPOINT_FW1_R55',
    name: 'Check Point Firewall-1 NG AI R55',
    category: SoftwareCategory.Security,
    licenseType: LicenseType.AnnualSubscription,
    vendor: 'Check Point',
    unlockYear: 2003,
    eosYear: 2015,
    annualCostNTD: 240_000,
    effects: [
      { type: SoftwareEffectType.SecurityDetection, value: 0.15 },
      { type: SoftwareEffectType.ComplianceScore, value: 10 },
    ],
    isFreeOpenSource: false,
  },
];

const ERA1_MONITORING: SoftwareProduct[] = [
  {
    id: 'NAGIOS_OSS',
    name: 'Nagios (Open Source)',
    category: SoftwareCategory.Monitoring,
    licenseType: LicenseType.OpenSource,
    vendor: 'Nagios Enterprises',
    unlockYear: 2000,
    eosYear: 9999,
    annualCostNTD: 0,
    effects: [
      { type: SoftwareEffectType.IncidentResponseTime, value: 0.10 },
    ],
    isFreeOpenSource: true,
    notes: 'Free monitoring, reduces incident response time 10%',
  },
];

const ERA1_DATABASE: SoftwareProduct[] = [
  {
    id: 'MYSQL_4',
    name: 'MySQL 4.x',
    category: SoftwareCategory.Database,
    licenseType: LicenseType.OpenSource,
    vendor: 'MySQL AB',
    unlockYear: 2000,
    eosYear: 2009,
    annualCostNTD: 0,
    effects: [],
    isFreeOpenSource: true,
  },
  {
    id: 'MSSQL_2000',
    name: 'Microsoft SQL Server 2000',
    category: SoftwareCategory.Database,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Microsoft',
    unlockYear: 2000,
    eosYear: 2013,
    annualCostNTD: 90_000,
    effects: [{ type: SoftwareEffectType.ComplianceScore, value: 5 }],
    isFreeOpenSource: false,
  },
  {
    id: 'ORACLE_9I',
    name: 'Oracle Database 9i',
    category: SoftwareCategory.Database,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Oracle',
    unlockYear: 2001,
    eosYear: 2010,
    annualCostNTD: 360_000,
    effects: [
      { type: SoftwareEffectType.ComplianceScore, value: 10 },
      { type: SoftwareEffectType.StoragePerformance, value: 1.3 },
    ],
    isFreeOpenSource: false,
    notes: 'Enterprise RDBMS, high cost/compliance',
  },
];

// ─── Era 2: 2005–2009 ────────────────────────────────────────────────────────

const ERA2_OS: SoftwareProduct[] = [
  {
    id: 'RHEL_5',
    name: 'Red Hat Enterprise Linux 5',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.AnnualSubscription,
    vendor: 'Red Hat',
    unlockYear: 2007,
    eosYear: 2020,
    annualCostNTD: 75_000,
    effects: [{ type: SoftwareEffectType.ComplianceScore, value: 7 }],
    isFreeOpenSource: false,
  },
  {
    id: 'CENTOS_5',
    name: 'CentOS 5',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.OpenSource,
    vendor: 'CentOS',
    unlockYear: 2007,
    eosYear: 2017,
    annualCostNTD: 0,
    effects: [],
    isFreeOpenSource: true,
    notes: 'RHEL 5 clone, zero cost, community support',
  },
  {
    id: 'WIN_SERVER_2008',
    name: 'Windows Server 2008',
    category: SoftwareCategory.OS,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Microsoft',
    unlockYear: 2008,
    eosYear: 2020,
    annualCostNTD: 90_000,
    effects: [{ type: SoftwareEffectType.ComplianceScore, value: 5 }],
    isFreeOpenSource: false,
  },
];

const ERA2_VIRTUALIZATION: SoftwareProduct[] = [
  {
    id: 'VMWARE_ESX_35',
    name: 'VMware ESX Server 3.5',
    category: SoftwareCategory.Virtualization,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'VMware',
    unlockYear: 2007,
    eosYear: 2013,
    annualCostNTD: 120_000,
    effects: [{ type: SoftwareEffectType.VirtualizationDensity, value: 3.0 }],
    isFreeOpenSource: false,
    notes: 'VMware Infrastructure 3.5, 3x VPS density',
  },
  {
    id: 'XEN_OSS',
    name: 'Xen 3.x (Open Source)',
    category: SoftwareCategory.Virtualization,
    licenseType: LicenseType.OpenSource,
    vendor: 'Xen Project',
    unlockYear: 2005,
    eosYear: 9999,
    annualCostNTD: 0,
    effects: [{ type: SoftwareEffectType.VirtualizationDensity, value: 2.2 }],
    isFreeOpenSource: true,
    notes: 'Open source hypervisor, 2.2x density',
  },
  {
    id: 'VMWARE_VI3',
    name: 'VMware Infrastructure 3',
    category: SoftwareCategory.Virtualization,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'VMware',
    unlockYear: 2006,
    eosYear: 2011,
    annualCostNTD: 105_000,
    effects: [{ type: SoftwareEffectType.VirtualizationDensity, value: 2.5 }],
    isFreeOpenSource: false,
    notes: 'VMotion, vCenter management, 2.5x density',
  },
];

const ERA2_BACKUP: SoftwareProduct[] = [
  {
    id: 'NETBACKUP_6',
    name: 'Veritas NetBackup 6',
    category: SoftwareCategory.Backup,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Veritas',
    unlockYear: 2005,
    eosYear: 2020,
    annualCostNTD: 180_000,
    effects: [{ type: SoftwareEffectType.BackupCoverage, value: 0.90 }],
    isFreeOpenSource: false,
  },
  {
    id: 'COMMVAULT_6',
    name: 'CommVault Simpana 6',
    category: SoftwareCategory.Backup,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'CommVault',
    unlockYear: 2006,
    eosYear: 2018,
    annualCostNTD: 120_000,
    effects: [{ type: SoftwareEffectType.BackupCoverage, value: 0.85 }],
    isFreeOpenSource: false,
    notes: 'Unified data protection platform',
  },
];

const ERA2_SECURITY: SoftwareProduct[] = [
  {
    id: 'SYMANTEC_SEP',
    name: 'Symantec Endpoint Protection',
    category: SoftwareCategory.Security,
    licenseType: LicenseType.AnnualSubscription,
    vendor: 'Symantec',
    unlockYear: 2007,
    eosYear: 2022,
    annualCostNTD: 150_000,
    effects: [
      { type: SoftwareEffectType.SecurityDetection, value: 0.18 },
      { type: SoftwareEffectType.ComplianceScore, value: 8 },
    ],
    isFreeOpenSource: false,
  },
  {
    id: 'CISCO_IPS_4255',
    name: 'Cisco IPS 4255',
    category: SoftwareCategory.Security,
    licenseType: LicenseType.AnnualSubscription,
    vendor: 'Cisco',
    unlockYear: 2005,
    eosYear: 2012,
    annualCostNTD: 200_000,
    effects: [
      { type: SoftwareEffectType.SecurityDetection, value: 0.25 },
      { type: SoftwareEffectType.ComplianceScore, value: 12 },
    ],
    isFreeOpenSource: false,
  },
];

const ERA2_MONITORING: SoftwareProduct[] = [
  {
    id: 'NAGIOS_XI',
    name: 'Nagios XI',
    category: SoftwareCategory.Monitoring,
    licenseType: LicenseType.AnnualSubscription,
    vendor: 'Nagios Enterprises',
    unlockYear: 2009,
    eosYear: 9999,
    annualCostNTD: 30_000,
    effects: [{ type: SoftwareEffectType.IncidentResponseTime, value: 0.18 }],
    isFreeOpenSource: false,
    notes: 'Commercial Nagios with web UI, better incident response',
  },
  {
    id: 'CACTI_OSS',
    name: 'Cacti (Open Source)',
    category: SoftwareCategory.Monitoring,
    licenseType: LicenseType.OpenSource,
    vendor: 'Cacti',
    unlockYear: 2005,
    eosYear: 9999,
    annualCostNTD: 0,
    effects: [{ type: SoftwareEffectType.IncidentResponseTime, value: 0.08 }],
    isFreeOpenSource: true,
    notes: 'Network graphing, free RRDtool frontend',
  },
];

const ERA2_DATABASE: SoftwareProduct[] = [
  {
    id: 'MYSQL_5',
    name: 'MySQL 5.x',
    category: SoftwareCategory.Database,
    licenseType: LicenseType.OpenSource,
    vendor: 'MySQL AB / Sun',
    unlockYear: 2005,
    eosYear: 2013,
    annualCostNTD: 0,
    effects: [],
    isFreeOpenSource: true,
    notes: 'Stored procedures, triggers, views support added',
  },
  {
    id: 'MSSQL_2005',
    name: 'Microsoft SQL Server 2005',
    category: SoftwareCategory.Database,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Microsoft',
    unlockYear: 2005,
    eosYear: 2016,
    annualCostNTD: 120_000,
    effects: [{ type: SoftwareEffectType.ComplianceScore, value: 6 }],
    isFreeOpenSource: false,
  },
  {
    id: 'ORACLE_10G',
    name: 'Oracle Database 10g',
    category: SoftwareCategory.Database,
    licenseType: LicenseType.PerpetualWithSA,
    vendor: 'Oracle',
    unlockYear: 2005,
    eosYear: 2013,
    annualCostNTD: 480_000,
    effects: [
      { type: SoftwareEffectType.ComplianceScore, value: 12 },
      { type: SoftwareEffectType.StoragePerformance, value: 1.5 },
    ],
    isFreeOpenSource: false,
    notes: 'Grid computing, RAC support',
  },
];

export const SOFTWARE_CATALOG: SoftwareProduct[] = [
  ...ERA1_OS,
  ...ERA1_VIRTUALIZATION,
  ...ERA1_BACKUP,
  ...ERA1_SECURITY,
  ...ERA1_MONITORING,
  ...ERA1_DATABASE,
  ...ERA2_OS,
  ...ERA2_VIRTUALIZATION,
  ...ERA2_BACKUP,
  ...ERA2_SECURITY,
  ...ERA2_MONITORING,
  ...ERA2_DATABASE,
];

export const SOFTWARE_CATALOG_BY_ID = new Map<string, SoftwareProduct>(
  SOFTWARE_CATALOG.map(p => [p.id, p]),
);
